<?php
/**
 * @file
 * Code for the Pub SSO feature.
 */

define('PUB_SSO_DEFAULT_PASSWORD_CHANGE_URL', 'https://sso.external.stg.nbcuni.com/nbcucentral/jsp/pwchange.jsp');

/**
 * Implements hook_menu().
 */
function pub_sso_menu() {
  $items = array();

  if (_simplesamlphp_auth_isEnabled()) {
    $items['sso'] = array(
      'title' => 'Log on to the site',
      'description' => 'Provides a site login page',
      'page callback' => 'simplesamlphp_auth_loginpage',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );

    if (variable_get('pub_sso_allow_deactivate_page', FALSE)) {
      $items['sso/deactivate'] = array(
        'title' => 'Deactivate SimpleSAML',
        'description' => 'Provides a page for deactivating the SimpleSAML functionality if the user is logged out.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('pub_sso_deactivate_page'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
      );
    }
  }

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function pub_sso_menu_alter(&$items) {
  if (_simplesamlphp_auth_isEnabled()) {
    $items['user']['page callback'] = 'simplesamlphp_auth_loginpage';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pub_sso_form_simplesamlphp_auth_settings_alter(&$form, &$form_state) {
  // This is tough for users to determine, provide the default for them.
  $simplesamlphp_installdir = str_replace('docroot', 'simplesamlphp', DRUPAL_ROOT);
  $installdir_title = $form['simplesamlphp_auth_grp_setup']['simplesamlphp_auth_installdir']['#title'];
  $form['simplesamlphp_auth_grp_setup']['simplesamlphp_auth_installdir']['#title'] = str_replace('/var/simplesamlphp', $simplesamlphp_installdir, $installdir_title);
  $form['simplesamlphp_auth_grp_setup']['simplesamlphp_auth_installdir']['#default_value'] = $simplesamlphp_installdir;

  // Determine the authentication source for this domain.
  include_once DRUPAL_ROOT . '/' . conf_path() . '/sso/domains.inc';
  if (array_key_exists($_SERVER['SERVER_NAME'], $domains)) {
    $simplesamlphp_authsource = $domains[$_SERVER['SERVER_NAME']];
    $authsource_title = $form['simplesamlphp_auth_grp_setup']['simplesamlphp_auth_authsource']['#title'];
    $form['simplesamlphp_auth_grp_setup']['simplesamlphp_auth_authsource']['#title'] = str_replace('default-sp', $simplesamlphp_authsource, $authsource_title);
    $form['simplesamlphp_auth_grp_setup']['simplesamlphp_auth_authsource']['#default_value'] = $simplesamlphp_authsource;
  }

  if (file_exists(_pub_sso_get_cert_directory() . '/sso.crt')) {
    $upload_description = t('A certificate exists for this instance of SimpleSAMLphp.');
  }
  else {
    $upload_description = t('You do not have a certificate applied.');
  }

  $form['#attributes']['enctype'] = 'multipart/form-data';
  $form['simplesamlphp_auth_grp_setup']['cert']['file_upload'] = array(
    '#title' => t('Upload certificate'),
    '#type'  => 'file',
    '#description'  => $upload_description,
  );

  // Disable set-up fields that have had values pre-supplied.
  $form['simplesamlphp_auth_grp_setup']['simplesamlphp_auth_installdir']['#disabled'] = TRUE;
  $form['simplesamlphp_auth_grp_setup']['simplesamlphp_auth_authsource']['#disabled'] = TRUE;
  // Move HTTPS checkbox to bottom of section and lock it from user editing.
  $form['simplesamlphp_auth_grp_setup']['simplesamlphp_auth_forcehttps']['#weight'] = 10;
  $form['simplesamlphp_auth_grp_setup']['simplesamlphp_auth_forcehttps']['#disabled'] = TRUE;

  // Set up defaults based upon values passed to us by SSO process.
  $form['simplesamlphp_auth_grp_user']['simplesamlphp_auth_user_name']['#default_value'] = 'email';
  $form['simplesamlphp_auth_grp_user']['simplesamlphp_auth_user_name']['#disabled'] = TRUE;
  $form['simplesamlphp_auth_grp_user']['simplesamlphp_auth_unique_id']['#default_value'] = 'uid';
  $form['simplesamlphp_auth_grp_user']['simplesamlphp_auth_unique_id']['#disabled'] = TRUE;
  $form['simplesamlphp_auth_grp_user']['simplesamlphp_auth_mailattr']['#default_value'] = 'email';
  $form['simplesamlphp_auth_grp_user']['simplesamlphp_auth_mailattr']['#disabled'] = TRUE;

  // Remove the role-related fields.
  $form['simplesamlphp_auth_grp_user']['simplesamlphp_auth_rolepopulation']['#access'] = FALSE;
  $form['simplesamlphp_auth_grp_user']['simplesamlphp_auth_roleevaleverytime']['#access'] = FALSE;

  // Hide the Drupal Authentication fieldset.
  $form['simplesamlphp_auth_grp_auth']['#access'] = FALSE;

  // Hide the User Provisioning fieldset.
  $form['simplesamlphp_auth_grp_reg']['simplesamlphp_auth_registerusers']['#default_value'] = 1;
  $form['simplesamlphp_auth_grp_reg']['#access'] = FALSE;

  // Add the submit handler.
  $form['#submit'][] = 'pub_sso_simplesamlphp_auth_form_submit';
}

/**
 * Implements hook_form_submit().
 */
function pub_sso_simplesamlphp_auth_form_submit($form, &$form_state) {
  $cert_directory = _pub_sso_get_cert_directory();
  $target_path = $cert_directory . '/sso.crt';

  // If we already have a cert and the user didn't supply another, don't go
  // through the save process.
  if (file_exists($target_path) && empty($_FILES['files']['tmp_name']['file_upload'])) {
    return;
  }

  $upload_result = move_uploaded_file($_FILES['files']['tmp_name']['file_upload'], $target_path);
  if (!$upload_result) {
    form_set_error('simplesamlphp_auth', t("Failed to save the file."));
  }
}

/**
 * Implements hook_block_view_alter().
 */
function pub_sso_block_view_alter(&$data, $block) {
  if (!_simplesamlphp_auth_isEnabled()) {
    if ($block->module === 'user' && $block->delta === 'login') {
      $block->visibility = 1;
    }

    return;
  }

  if ($block->module === 'user' && $block->delta === 'login') {
    $block->visibility = 0;
    $data['content'] = FALSE;
  }
  if ($block->module === 'simplesamlphp_auth' && is_array($data)) {
    if (user_is_logged_in()) {
      $block->visibility = 0;
    }
    else {
      $data['content'] = '<p>' . l(t('Log in with your SSO'), 'saml_login') . '</p>';
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pub_sso_form_user_register_form_alter(&$form, &$form_state) {
  $form['account']['name']['#access'] = FALSE;
  $form['account']['name']['#required'] = FALSE;

  $form['account']['mail']['#weight'] = -10;

  $form['account']['pass']['#access'] = FALSE;
  $form['account']['pass']['#required'] = FALSE;

  array_unshift($form['#validate'], 'pub_sso_form_user_register_validate');
}

/**
 * Validation handler for the user register form.
 *
 * @see pub_sso_form_user_register_form_alter
 */
function pub_sso_form_user_register_validate($form, &$form_state) {
  // Set the username to the email address, prior to user validation.
  $form_state['values']['name'] = $form_state['values']['mail'];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pub_sso_form_user_profile_form_alter(&$form, &$form_state) {
  global $user;

  if (!_simplesamlphp_auth_isEnabled()) {
    // Exit without executing.
    return;
  }

  $form['account']['name']['#disabled'] = TRUE;
  $form['account']['pass']['#access'] = FALSE;
  $form['account']['current_pass']['#access'] = FALSE;

  if (isset($user->uid) && $user->uid == 1) {
    $form['password_policy']['#access'] = FALSE;
  }
  else {
    $form['account']['mail']['#disabled'] = TRUE;
    $form['account']['mail']['#weight'] = -8;

    $password_url = variable_get('pub_sso_password_reset', PUB_SSO_DEFAULT_PASSWORD_CHANGE_URL);
    $password_link = l(t('Change your password'), $password_url, array(
        'attributes' => array(
          'target' => 'blank',
        )));
    $form['account']['change_password'] = array(
      '#markup' => $password_link,
      '#weight' => -5,
    );

    $form['password_policy']['#access'] = FALSE;
  }
}

/**
 * Implements hook_user_presave().
 */
function pub_sso_user_presave(&$edit, $account, $category) {
  if (!_simplesamlphp_auth_isEnabled()) {
    // Exit without executing.
    return;
  }

  $edit['data'] = array(
    'pub_sso' => array(),
  );

  $saml_attributes = simplesamlphp_auth_get_attributes();
  if (isset($saml_attributes['FirstName'])) {
    $edit['data']['pub_sso']['FirstName'] = $saml_attributes['FirstName'];
  }
  if (isset($saml_attributes['LastName'])) {
    $edit['data']['pub_sso']['LastName'] = $saml_attributes['LastName'];
  }
}

/**
 * Create the form for deactivating SimpleSAML.
 */
function pub_sso_deactivate_page($form, &$form_state) {
  if (variable_get('simplesamlphp_auth_activate', FALSE)) {
    $form['deactivate_button'] = array(
      '#type' => 'submit',
      '#value' => t('Deactivate'),
    );
  }
  else {
    drupal_set_message('The SimpleSAML module is deactivated.');
    drupal_goto('<front>');
  }

  return $form;
}

/**
 * Submit handler for the deactivate page.
 *
 * @see pub_sso_deactivate_page()
 */
function pub_sso_deactivate_page_submit($form, &$form_state) {
  variable_set('simplesamlphp_auth_activate', FALSE);
}

/**
 * Implements hook_simplesamlphp_auth_addauthmaps_alter().
 *
 * The Simplesamlphp Auth module attempts to find an existing user by name.
 * That won't work for us; we use the email address as the identifier instead.
 */
function pub_sso_simplesamlphp_auth_addauthmaps_alter(&$existing_user, $context) {
  if (empty($existing_user) && !empty($context['simplesamlphp_auth_saml_attributes']['email'])) {
    $email = $context['simplesamlphp_auth_saml_attributes']['email'];
    $user = user_load_by_mail($email);
    $existing_user = $user == FALSE ? NULL : $user;
  }
}

/**
 * A utility function for determining where SSO certificates should be stored.
 */
function _pub_sso_get_cert_directory() {
  // We need to find a directory we can write the certificate to.
  $files_private_directory = variable_get('file_private_path', FALSE);
  if (!empty($files_private_directory) && is_writable($files_private_directory)) {
    return $files_private_directory . '/sso_cert';
  }
  return FALSE;
}
